### ISSUE TITLE
Grafana no Data base with this name

### ISSUE THREAD

**Issue by JuXReal** [jammsen/docker-collectd-fritzbox#1]
All containers are up and Running. 

If I try to add a source in Grafan I get the Message:
No Data base with this name found. 

I tryed: collectd , influxdb  and so on. 

Wich settings I need for Graphana Source?

```
`# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - F:\grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db
      - /mnt/user/appdata/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "25826:25826/udp"

  collectd:
    image: jammsen/collectd-fritzbox:latest
    network_mode: host
    container_name: collectd-fritzbox
    environment:
      - TIMEZONE=Europe/Berlin
      - CheckInterval=3
      - InfluxDbIp=127.0.0.1
      - InfluxDbCollectdPort=25826
      - FritzBoxIp=192.168.178.1
      - FritzBoxUser=collectd
      - FritzBoxPassword=collectd
    depends_on:
      - influxdb`
```
